//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/InputSystem/PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerController"",
    ""maps"": [
        {
            ""name"": ""Move"",
            ""id"": ""841e37ef-8f89-4829-8a39-8b7f798c9c18"",
            ""actions"": [
                {
                    ""name"": ""Apuntar"",
                    ""type"": ""Button"",
                    ""id"": ""2d96c0f6-1054-4db2-82ea-743f87c82401"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Disparar"",
                    ""type"": ""Button"",
                    ""id"": ""83312c27-26f0-4f1b-966e-fd27e676134e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventario"",
                    ""type"": ""Button"",
                    ""id"": ""f2a3e482-08cc-4fc0-a3e5-6404235c9673"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Borrar"",
                    ""type"": ""Button"",
                    ""id"": ""86e74ddd-7b1b-4145-ad7b-98fd304e643b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Izquierda"",
                    ""type"": ""Button"",
                    ""id"": ""6f8b1b80-4c48-4eb3-a74d-b53f13e21d44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Derecha"",
                    ""type"": ""Button"",
                    ""id"": ""228397ba-6847-4f91-8a82-0f8bb3d5ccd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Adelante"",
                    ""type"": ""Button"",
                    ""id"": ""aca86546-bd51-4106-9e87-c5795b0ff36c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Atras"",
                    ""type"": ""Button"",
                    ""id"": ""757820fc-b372-4bdc-88c7-11943b078dda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Agachar"",
                    ""type"": ""Button"",
                    ""id"": ""a790dc0c-88eb-41c4-add8-987ce4875eda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""1ce0c0ca-bbc7-4931-b5ca-45eaced05e0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""96db931b-106d-4bbd-ba4e-8df283867d5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""b8dedfbc-d7df-4970-bda4-d63ffaca9d38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaccion"",
                    ""type"": ""Button"",
                    ""id"": ""f2956a11-da70-422e-bd63-36103fb17622"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Recarga"",
                    ""type"": ""Button"",
                    ""id"": ""75983e14-3c7e-4de7-a73e-e1a78fa81acb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Destinos"",
                    ""type"": ""Button"",
                    ""id"": ""bc937bfa-44f7-437b-8221-ba79e9beef42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SituacionActual"",
                    ""type"": ""Button"",
                    ""id"": ""52366fc3-ed77-4da0-8235-5d5316eb215e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6663b35a-2fcd-4edc-98d4-ee744ddb477e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Izquierda"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7de17086-8b70-4b6e-8c29-14fe9c06ad04"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Derecha"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2a323a7-0290-43ad-bd1f-42914952dd8e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adelante"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""477d5a25-474f-4af1-8dd0-4951c99a6070"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f3cf680-9f7d-40f8-84a3-de4bd54cfad3"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Agachar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bef9be5d-4f28-4281-b189-a9682c9b8a6d"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""443a89f2-da27-4b73-9b37-5bd5f36a1d3e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97141f52-43c4-4389-a618-e483e996acc7"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Apuntar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc2f57d4-1124-4cfb-bb7f-9430f35df2fd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Disparar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5634472-936e-452e-8168-6a539d2f0353"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventario"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d299230f-69db-4bb9-8c28-65131ba69e6b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Borrar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42504859-46af-49ab-803d-501c31b1af92"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40c6860e-af68-49de-9ab9-1b85282c6758"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaccion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af43a10b-848e-4c7e-a304-749a9210f696"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recarga"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""772b2baa-ae42-4107-b921-a15d35a52b5a"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Destinos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14b45124-52e1-405a-96a2-7b31b9fe2975"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SituacionActual"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Move
        m_Move = asset.FindActionMap("Move", throwIfNotFound: true);
        m_Move_Apuntar = m_Move.FindAction("Apuntar", throwIfNotFound: true);
        m_Move_Disparar = m_Move.FindAction("Disparar", throwIfNotFound: true);
        m_Move_Inventario = m_Move.FindAction("Inventario", throwIfNotFound: true);
        m_Move_Borrar = m_Move.FindAction("Borrar", throwIfNotFound: true);
        m_Move_Izquierda = m_Move.FindAction("Izquierda", throwIfNotFound: true);
        m_Move_Derecha = m_Move.FindAction("Derecha", throwIfNotFound: true);
        m_Move_Adelante = m_Move.FindAction("Adelante", throwIfNotFound: true);
        m_Move_Atras = m_Move.FindAction("Atras", throwIfNotFound: true);
        m_Move_Agachar = m_Move.FindAction("Agachar", throwIfNotFound: true);
        m_Move_Sprint = m_Move.FindAction("Sprint", throwIfNotFound: true);
        m_Move_Saltar = m_Move.FindAction("Saltar", throwIfNotFound: true);
        m_Move_Menu = m_Move.FindAction("Menu", throwIfNotFound: true);
        m_Move_Interaccion = m_Move.FindAction("Interaccion", throwIfNotFound: true);
        m_Move_Recarga = m_Move.FindAction("Recarga", throwIfNotFound: true);
        m_Move_Destinos = m_Move.FindAction("Destinos", throwIfNotFound: true);
        m_Move_SituacionActual = m_Move.FindAction("SituacionActual", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Move
    private readonly InputActionMap m_Move;
    private IMoveActions m_MoveActionsCallbackInterface;
    private readonly InputAction m_Move_Apuntar;
    private readonly InputAction m_Move_Disparar;
    private readonly InputAction m_Move_Inventario;
    private readonly InputAction m_Move_Borrar;
    private readonly InputAction m_Move_Izquierda;
    private readonly InputAction m_Move_Derecha;
    private readonly InputAction m_Move_Adelante;
    private readonly InputAction m_Move_Atras;
    private readonly InputAction m_Move_Agachar;
    private readonly InputAction m_Move_Sprint;
    private readonly InputAction m_Move_Saltar;
    private readonly InputAction m_Move_Menu;
    private readonly InputAction m_Move_Interaccion;
    private readonly InputAction m_Move_Recarga;
    private readonly InputAction m_Move_Destinos;
    private readonly InputAction m_Move_SituacionActual;
    public struct MoveActions
    {
        private @PlayerController m_Wrapper;
        public MoveActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Apuntar => m_Wrapper.m_Move_Apuntar;
        public InputAction @Disparar => m_Wrapper.m_Move_Disparar;
        public InputAction @Inventario => m_Wrapper.m_Move_Inventario;
        public InputAction @Borrar => m_Wrapper.m_Move_Borrar;
        public InputAction @Izquierda => m_Wrapper.m_Move_Izquierda;
        public InputAction @Derecha => m_Wrapper.m_Move_Derecha;
        public InputAction @Adelante => m_Wrapper.m_Move_Adelante;
        public InputAction @Atras => m_Wrapper.m_Move_Atras;
        public InputAction @Agachar => m_Wrapper.m_Move_Agachar;
        public InputAction @Sprint => m_Wrapper.m_Move_Sprint;
        public InputAction @Saltar => m_Wrapper.m_Move_Saltar;
        public InputAction @Menu => m_Wrapper.m_Move_Menu;
        public InputAction @Interaccion => m_Wrapper.m_Move_Interaccion;
        public InputAction @Recarga => m_Wrapper.m_Move_Recarga;
        public InputAction @Destinos => m_Wrapper.m_Move_Destinos;
        public InputAction @SituacionActual => m_Wrapper.m_Move_SituacionActual;
        public InputActionMap Get() { return m_Wrapper.m_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveActions set) { return set.Get(); }
        public void SetCallbacks(IMoveActions instance)
        {
            if (m_Wrapper.m_MoveActionsCallbackInterface != null)
            {
                @Apuntar.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnApuntar;
                @Apuntar.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnApuntar;
                @Apuntar.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnApuntar;
                @Disparar.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnDisparar;
                @Disparar.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnDisparar;
                @Disparar.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnDisparar;
                @Inventario.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnInventario;
                @Inventario.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnInventario;
                @Inventario.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnInventario;
                @Borrar.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnBorrar;
                @Borrar.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnBorrar;
                @Borrar.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnBorrar;
                @Izquierda.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnIzquierda;
                @Izquierda.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnIzquierda;
                @Izquierda.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnIzquierda;
                @Derecha.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnDerecha;
                @Derecha.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnDerecha;
                @Derecha.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnDerecha;
                @Adelante.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnAdelante;
                @Adelante.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnAdelante;
                @Adelante.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnAdelante;
                @Atras.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnAtras;
                @Atras.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnAtras;
                @Atras.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnAtras;
                @Agachar.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnAgachar;
                @Agachar.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnAgachar;
                @Agachar.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnAgachar;
                @Sprint.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnSprint;
                @Saltar.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnSaltar;
                @Saltar.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnSaltar;
                @Saltar.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnSaltar;
                @Menu.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnMenu;
                @Interaccion.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnInteraccion;
                @Interaccion.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnInteraccion;
                @Interaccion.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnInteraccion;
                @Recarga.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnRecarga;
                @Recarga.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnRecarga;
                @Recarga.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnRecarga;
                @Destinos.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnDestinos;
                @Destinos.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnDestinos;
                @Destinos.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnDestinos;
                @SituacionActual.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnSituacionActual;
                @SituacionActual.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnSituacionActual;
                @SituacionActual.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnSituacionActual;
            }
            m_Wrapper.m_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Apuntar.started += instance.OnApuntar;
                @Apuntar.performed += instance.OnApuntar;
                @Apuntar.canceled += instance.OnApuntar;
                @Disparar.started += instance.OnDisparar;
                @Disparar.performed += instance.OnDisparar;
                @Disparar.canceled += instance.OnDisparar;
                @Inventario.started += instance.OnInventario;
                @Inventario.performed += instance.OnInventario;
                @Inventario.canceled += instance.OnInventario;
                @Borrar.started += instance.OnBorrar;
                @Borrar.performed += instance.OnBorrar;
                @Borrar.canceled += instance.OnBorrar;
                @Izquierda.started += instance.OnIzquierda;
                @Izquierda.performed += instance.OnIzquierda;
                @Izquierda.canceled += instance.OnIzquierda;
                @Derecha.started += instance.OnDerecha;
                @Derecha.performed += instance.OnDerecha;
                @Derecha.canceled += instance.OnDerecha;
                @Adelante.started += instance.OnAdelante;
                @Adelante.performed += instance.OnAdelante;
                @Adelante.canceled += instance.OnAdelante;
                @Atras.started += instance.OnAtras;
                @Atras.performed += instance.OnAtras;
                @Atras.canceled += instance.OnAtras;
                @Agachar.started += instance.OnAgachar;
                @Agachar.performed += instance.OnAgachar;
                @Agachar.canceled += instance.OnAgachar;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Saltar.started += instance.OnSaltar;
                @Saltar.performed += instance.OnSaltar;
                @Saltar.canceled += instance.OnSaltar;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @Interaccion.started += instance.OnInteraccion;
                @Interaccion.performed += instance.OnInteraccion;
                @Interaccion.canceled += instance.OnInteraccion;
                @Recarga.started += instance.OnRecarga;
                @Recarga.performed += instance.OnRecarga;
                @Recarga.canceled += instance.OnRecarga;
                @Destinos.started += instance.OnDestinos;
                @Destinos.performed += instance.OnDestinos;
                @Destinos.canceled += instance.OnDestinos;
                @SituacionActual.started += instance.OnSituacionActual;
                @SituacionActual.performed += instance.OnSituacionActual;
                @SituacionActual.canceled += instance.OnSituacionActual;
            }
        }
    }
    public MoveActions @Move => new MoveActions(this);
    public interface IMoveActions
    {
        void OnApuntar(InputAction.CallbackContext context);
        void OnDisparar(InputAction.CallbackContext context);
        void OnInventario(InputAction.CallbackContext context);
        void OnBorrar(InputAction.CallbackContext context);
        void OnIzquierda(InputAction.CallbackContext context);
        void OnDerecha(InputAction.CallbackContext context);
        void OnAdelante(InputAction.CallbackContext context);
        void OnAtras(InputAction.CallbackContext context);
        void OnAgachar(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnSaltar(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnInteraccion(InputAction.CallbackContext context);
        void OnRecarga(InputAction.CallbackContext context);
        void OnDestinos(InputAction.CallbackContext context);
        void OnSituacionActual(InputAction.CallbackContext context);
    }
}
